// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxhwQxp3HO0PcZVEcTSYugDxwvkhYJSk',
    appId: '1:22355493272:web:570c8cbb0f23658fd0ebed',
    messagingSenderId: '22355493272',
    projectId: 'mobilen3-2675c',
    authDomain: 'mobilen3-2675c.firebaseapp.com',
    storageBucket: 'mobilen3-2675c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN1eprcVrcpac2i4EJWMqmBDZYIghk9Og',
    appId: '1:22355493272:android:d679fb95e4e0b94cd0ebed',
    messagingSenderId: '22355493272',
    projectId: 'mobilen3-2675c',
    storageBucket: 'mobilen3-2675c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuxhwQxp3HO0PcZVEcTSYugDxwvkhYJSk',
    appId: '1:22355493272:web:73b2489840ca859dd0ebed',
    messagingSenderId: '22355493272',
    projectId: 'mobilen3-2675c',
    authDomain: 'mobilen3-2675c.firebaseapp.com',
    storageBucket: 'mobilen3-2675c.firebasestorage.app',
  );
}
